"""The npm side, which is data and nothing else.

`package.json` is generated by `build-artifacts.py` for the same reason every
other JSON here is. No file in this repository is authored by hand, and build
metadata is not an exception to that.
"""

from __future__ import annotations

import json
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
MANIFEST = REPO / "package.json"


def manifest() -> dict[str, object]:
    return dict(json.loads(MANIFEST.read_text(encoding="utf-8")))


def test_it_is_named_the_same_on_both_registries() -> None:
    """A reader who found one has to be able to guess the other."""
    assert manifest()["name"] == "the-catholic-bible"


def test_it_carries_no_dependencies() -> None:
    """The epic's constraint. Data only, and nothing to install behind it."""
    found = manifest()

    assert "dependencies" not in found
    assert "peerDependencies" not in found


def test_the_entry_point_is_the_file_that_says_what_exists() -> None:
    """`require('the-catholic-bible')` answering with the index is the whole
    ergonomics of a data package. `index.json` already answers that question
    for CDN readers and it is the same question here."""
    assert manifest()["main"] == "data/index.json"


def test_the_tarball_carries_the_data_and_the_terms() -> None:
    """Without `files`, npm ships the whole checkout, tests and scripts and all.

    The licence has to travel because the corpus is not MIT and CC BY 4.0
    wants its notice present wherever the bytes go.

    Both READMEs are listed because npm ships every `README*` whatever this
    field says. `npm pack --dry-run` put the Portuguese one in a tarball the
    manifest did not mention, which is a manifest describing something else.
    """
    files = manifest()["files"]

    assert "data" in files  # type: ignore[operator]
    assert "LICENSE" in files  # type: ignore[operator]
    assert "README.md" in files  # type: ignore[operator]
    assert "README.pt-BR.md" in files  # type: ignore[operator]


def test_it_does_not_claim_one_licence_over_a_mixed_bundle() -> None:
    """MIT would relicense somebody else's public domain and drop CC BY."""
    assert manifest()["license"] == "SEE LICENSE IN LICENSE"


def test_the_repository_is_named_so_provenance_can_be_checked() -> None:
    """`npm publish --provenance` signs against this, and a reader compares."""
    repository = manifest()["repository"]

    assert "ronaldoscotti/catholic-bible" in json.dumps(repository)


def test_the_version_is_the_same_number_in_all_five_places() -> None:
    """One number, two generators, and the failure mode is silence.

    `build-artifacts.py` writes three of these from `pyproject.toml`.
    `openapi.json` gets there separately, through FastAPI reading
    `__version__`, so trusting the generator would leave that one unchecked.

    `LIMITS.md` was wrong for two epics because prose and data had no
    mechanism holding them together. Five files agreeing by convention is the
    same arrangement.
    """
    pyproject = tomllib.loads((REPO / "pyproject.toml").read_text(encoding="utf-8"))
    wanted = pyproject["project"]["version"]

    def published(name: str, key: str) -> object:
        return json.loads((REPO / name).read_text(encoding="utf-8"))[key]

    assert manifest()["version"] == wanted
    assert published("data/index.json", "dataset_version") == wanted
    assert published("data/manifest.json", "dataset_version") == wanted
    assert (
        json.loads((REPO / "openapi.json").read_text(encoding="utf-8"))["info"][
            "version"
        ]
        == wanted
    )
