"""The published artifact tree, checked against what it was split from.

These read `data/` at the repository root, which is generated by
`scripts/build-artifacts.py` and committed. Nothing here reads the private
source, so a stranger on a clean checkout runs all of it.

The test that matters most is `test_the_split_loses_no_verse`. A partition bug
drops a book while every count in the tree stays plausible.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest

from catholic_bible.canon.books import CANON

ROOT = Path(__file__).resolve().parent.parent.parent
DATA = ROOT / "data"
SOURCE = ROOT / "src" / "catholic_bible" / "data"

VERSIONS = ("matos-soares", "douay-rheims", "vulgata-clementina")
BOOKS = tuple(book.code for book in CANON)


def read(path: Path) -> dict[str, object]:
    loaded: dict[str, object] = json.loads(path.read_text(encoding="utf-8"))
    return loaded


def source(name: str) -> dict[str, object]:
    return read(SOURCE / name)


def test_every_version_publishes_all_73_books() -> None:
    for code in VERSIONS:
        published = sorted(
            p.stem for p in (DATA / "versions" / code / "books").glob("*.json")
        )
        assert published == sorted(BOOKS), code


def test_the_split_loses_no_verse() -> None:
    for code in VERSIONS:
        monolith = source(f"corpus/{code}.json")["verses"]
        assert isinstance(monolith, dict)
        rebuilt: dict[str, object] = {}
        for book in BOOKS:
            verses = read(DATA / "versions" / code / "books" / f"{book}.json")["verses"]
            assert isinstance(verses, dict)
            overlap = rebuilt.keys() & verses.keys()
            assert not overlap, f"{code} {book} repeats {sorted(overlap)[:3]}"
            rebuilt.update(verses)
        assert rebuilt == monolith, code


def test_a_verse_lands_in_the_book_it_names() -> None:
    for code in VERSIONS:
        for book in BOOKS:
            verses = read(DATA / "versions" / code / "books" / f"{book}.json")["verses"]
            assert isinstance(verses, dict)
            stray = [key for key in verses if key.split(".")[0] != book]
            assert not stray, f"{code} {book} carries {stray[:3]}"


def test_rights_travel_inside_every_published_file() -> None:
    """A static file has no envelope, so the licence rides in the file itself."""
    for code in VERSIONS:
        for book in BOOKS:
            document = read(DATA / "versions" / code / "books" / f"{book}.json")
            version = document["version"]
            assert isinstance(version, dict)
            rights = version["rights"]
            assert isinstance(rights, dict)
            assert rights["text"] and rights["text_basis"]


@pytest.mark.parametrize(
    ("version", "book", "name", "abbreviation"),
    [
        ("vulgata-clementina", "JOS", "Iosue", "Ios."),
        ("douay-rheims", "JOS", "Josue", "Jos."),
        ("matos-soares", "JOS", "Josué", "Js"),
        ("vulgata-clementina", "SIR", "Ecclesiasticus", "Eccli."),
        ("douay-rheims", "SIR", "Ecclesiasticus", "Ecclus."),
        ("matos-soares", "SIR", "Eclesiástico", "Eclo"),
    ],
)
def test_the_book_block_is_named_in_the_language_of_the_version(
    version: str, book: str, name: str, abbreviation: str
) -> None:
    """Sirach is Ecclesiasticus in both Latin and Douay English, and that is
    the tradition rather than a bug. The abbreviation is where they part."""
    block = read(DATA / "versions" / version / "books" / f"{book}.json")["book"]
    assert isinstance(block, dict)
    assert block["name"] == name
    assert block["abbreviation"] == abbreviation


def test_a_deuterocanonical_book_says_so() -> None:
    block = read(DATA / "versions" / "matos-soares" / "books" / "SIR.json")["book"]
    assert isinstance(block, dict)
    assert block["deuterocanonical"] is True
    assert block["chapters"] == 51


def test_the_commentary_splits_without_losing_an_entry() -> None:
    monolith = source("commentary/haydock.json")["entries"]
    assert isinstance(monolith, list)
    rebuilt = 0
    for book in BOOKS:
        entries = read(DATA / "commentary" / "haydock" / "books" / f"{book}.json")[
            "entries"
        ]
        assert isinstance(entries, list)
        rebuilt += len(entries)
    assert rebuilt == len(monolith) == 20705


def test_no_published_commentary_body_carries_a_pipeline_marker() -> None:
    """B4 shipped 244 bodies with the translation harness's markers in them.

    The export cuts them and the build refuses them. This is the third gate and
    it reads the file a consumer actually downloads.
    """
    for book in BOOKS:
        raw = (DATA / "commentary" / "haydock" / "books" / f"{book}.json").read_text(
            encoding="utf-8"
        )
        assert "[[[" not in raw, book


def test_the_only_published_commentary_is_haydock() -> None:
    """The Catena Aurea shares the source tables and must never ship."""
    published = sorted(p.name for p in (DATA / "commentary").iterdir())
    assert published == ["haydock"]


def test_the_cross_references_split_without_losing_a_reference() -> None:
    monolith = source("cross-references/references.json")["references"]
    assert isinstance(monolith, dict)
    counted = sum(len(records) for records in monolith.values())
    rebuilt, anchors = 0, 0
    for book in BOOKS:
        references = read(DATA / "cross-references" / "books" / f"{book}.json")[
            "references"
        ]
        assert isinstance(references, dict)
        anchors += len(references)
        rebuilt += sum(len(records) for records in references.values())
    assert rebuilt == counted
    assert anchors == len(monolith)


def test_the_openbible_attribution_rides_in_all_73_files() -> None:
    """CC BY requires attribution to travel with the data.

    An HTTP response carries it in an envelope. A file that gets copied into
    somebody's project keeps its provenance or loses it forever.
    """
    for book in BOOKS:
        sources = read(DATA / "cross-references" / "books" / f"{book}.json")["sources"]
        assert isinstance(sources, dict)
        openbible = sources["openbible"]
        assert isinstance(openbible, dict)
        assert "OpenBible" in str(openbible["attribution"]), book
        assert openbible["rights"] == "CC BY 4.0"


def test_the_ave_maria_apparatus_reaches_no_published_file() -> None:
    for book in BOOKS:
        raw = (DATA / "cross-references" / "books" / f"{book}.json").read_text(
            encoding="utf-8"
        )
        assert "ave-maria" not in raw, book


def test_the_deuterocanonical_books_carry_cross_references() -> None:
    """The reason this epic exists. OpenBible reaches none of these."""
    for book in ("WIS", "SIR", "TOB", "1MA"):
        references = read(DATA / "cross-references" / "books" / f"{book}.json")[
            "references"
        ]
        assert isinstance(references, dict)
        assert references, book


@pytest.mark.parametrize(
    ("published", "origin"),
    [
        ("canon.json", "canon.json"),
        ("spine.json", "versification.json"),
        ("orphans.json", "derived/orphans.json"),
        ("coverage.json", "derived/coverage.json"),
    ],
)
def test_the_small_artifacts_are_copies_and_not_rewrites(
    published: str, origin: str
) -> None:
    assert read(DATA / published) == source(origin)


def test_the_manifest_checksums_recompute() -> None:
    manifest = read(DATA / "manifest.json")
    files = manifest["files"]
    assert isinstance(files, dict)
    for name, record in files.items():
        assert isinstance(record, dict)
        payload = (DATA / name).read_bytes()
        assert hashlib.sha256(payload).hexdigest() == record["sha256"], name
        assert len(payload) == record["bytes"], name


def test_the_manifest_lists_every_file_in_the_tree() -> None:
    """A file nobody can verify is worse than a file that is not published."""
    manifest = read(DATA / "manifest.json")
    files = manifest["files"]
    assert isinstance(files, dict)
    on_disk = {
        str(path.relative_to(DATA))
        for path in DATA.rglob("*.json")
        if path.name != "manifest.json"
    }
    assert on_disk == set(files)


def test_the_index_advertises_nothing_that_is_missing() -> None:
    index = read(DATA / "index.json")
    versions = index["versions"]
    commentaries = index["commentaries"]
    assert isinstance(versions, list) and isinstance(commentaries, list)
    for record in [*versions, *commentaries]:
        assert isinstance(record, dict)
        for book in BOOKS:
            path = str(record["books"]).replace("{book}", book)
            assert (DATA / path).is_file(), path


def test_no_artifact_carries_catechism_text() -> None:
    """B11 publishes paragraph numbers and links. Never the words.

    This asserted that no artifact mentions `vatican.va`, which held while the
    Catechism was absent and inverted the day it arrived, since a link to the
    official text is the whole point. What it asserts now is the shape, because
    a paragraph's text, title, first line or summary would have to be a field
    that is not a number, an address, a short citation label or a page URL.

    The count is asserted first. A sweep over a tree that does not exist yet
    passes every content check it makes.
    """
    paths = list(DATA.rglob("*.json"))
    assert len(paths) == 447

    citations = [
        path
        for path in paths
        if path.parent.name == "books" and path.parent.parent.name == "catechism"
    ]
    assert len(citations) == len(BOOKS)

    for path in citations:
        published = read(path)
        assert set(published) == {"rights", "pages", "book", "citations"}
        entries = published["citations"]
        assert isinstance(entries, dict)
        for records in entries.values():
            assert isinstance(records, list)
            for record in records:
                assert set(record) == {"paragraph", "cited"}
                assert isinstance(record["paragraph"], int)
                # A citation label. Prose does not fit in thirty two characters.
                assert len(str(record["cited"])) < 32, record

    pages = read(DATA / "catechism" / "pages.json")
    editions = pages["editions"]
    assert isinstance(editions, dict)
    for edition in editions.values():
        assert str(edition["base"]).startswith("https://www.vatican.va/archive/")
        for page in edition["pages"]:
            assert set(page) == {"file", "first"}
