"""Book names authored here rather than exported.

Everything else in this package comes out of the private source repository. Two
things do not exist there and are written here instead, so they live in code
where a reviewer reads them as a decision rather than in JSON where they would
look like data somebody generated.

Latin follows liturgical usage. Where the tradition carries more than one form
the liturgical one is canonical and the alternative is an alias, so nothing is
decided by silence. The books of Kings keep the Vulgate reckoning, in which
I and II Regum are Samuel, which is the same reckoning the Douay names use.

Modern English is here because the exported Douay names are the canonical
English and a reader who types `Joshua` should still land in Josue.
"""

LATIN_NAMES = {
    "GEN": "Genesis",
    "EXO": "Exodus",
    "LEV": "Leviticus",
    "NUM": "Numeri",
    "DEU": "Deuteronomium",
    "JOS": "Iosue",
    "JDG": "Iudicum",
    "RUT": "Ruth",
    "1SA": "I Regum",
    "2SA": "II Regum",
    "1KI": "III Regum",
    "2KI": "IV Regum",
    "1CH": "I Paralipomenon",
    "2CH": "II Paralipomenon",
    "EZR": "Esdrae",
    "NEH": "Nehemiae",
    "TOB": "Tobiae",
    "JDT": "Iudith",
    "EST": "Esther",
    "1MA": "I Machabaeorum",
    "2MA": "II Machabaeorum",
    "JOB": "Iob",
    "PSA": "Psalmi",
    "PRO": "Proverbia",
    "ECC": "Ecclesiastes",
    "SNG": "Canticum Canticorum",
    "WIS": "Sapientia",
    "SIR": "Ecclesiasticus",
    "ISA": "Isaias",
    "JER": "Ieremias",
    "LAM": "Lamentationes",
    "BAR": "Baruch",
    "EZK": "Ezechiel",
    "DAN": "Daniel",
    "HOS": "Osee",
    "JOL": "Ioel",
    "AMO": "Amos",
    "OBA": "Abdias",
    "JON": "Ionas",
    "MIC": "Michaeas",
    "NAM": "Nahum",
    "HAB": "Habacuc",
    "ZEP": "Sophonias",
    "HAG": "Aggaeus",
    "ZEC": "Zacharias",
    "MAL": "Malachias",
    "MAT": "Matthaeus",
    "MRK": "Marcus",
    "LUK": "Lucas",
    "JHN": "Ioannes",
    "ACT": "Actus Apostolorum",
    "ROM": "Ad Romanos",
    "1CO": "I Ad Corinthios",
    "2CO": "II Ad Corinthios",
    "GAL": "Ad Galatas",
    "EPH": "Ad Ephesios",
    "PHP": "Ad Philippenses",
    "COL": "Ad Colossenses",
    "1TH": "I Ad Thessalonicenses",
    "2TH": "II Ad Thessalonicenses",
    "1TI": "I Ad Timotheum",
    "2TI": "II Ad Timotheum",
    "TIT": "Ad Titum",
    "PHM": "Ad Philemonem",
    "HEB": "Ad Hebraeos",
    "JAS": "Iacobi",
    "1PE": "I Petri",
    "2PE": "II Petri",
    "1JN": "I Ioannis",
    "2JN": "II Ioannis",
    "3JN": "III Ioannis",
    "JUD": "Iudae",
    "REV": "Apocalypsis",
}

LATIN_ALIASES = {
    "1SA": ("I Samuelis",),
    "2SA": ("II Samuelis",),
    "NEH": ("II Esdrae",),
    "EZR": ("I Esdrae",),
    "SIR": ("Siracides", "Liber Ecclesiastici"),
    "SNG": ("Canticum", "Cantica Canticorum"),
    "REV": ("Revelatio",),
    "LAM": ("Threni",),
    "ECC": ("Qoheleth",),
    "ACT": ("Acta Apostolorum",),
}

ENGLISH_MODERN = {
    "GEN": "Genesis",
    "EXO": "Exodus",
    "LEV": "Leviticus",
    "NUM": "Numbers",
    "DEU": "Deuteronomy",
    "JOS": "Joshua",
    "JDG": "Judges",
    "RUT": "Ruth",
    "1SA": "1 Samuel",
    "2SA": "2 Samuel",
    "1KI": "1 Kings",
    "2KI": "2 Kings",
    "1CH": "1 Chronicles",
    "2CH": "2 Chronicles",
    "EZR": "Ezra",
    "NEH": "Nehemiah",
    "TOB": "Tobit",
    "JDT": "Judith",
    "EST": "Esther",
    "1MA": "1 Maccabees",
    "2MA": "2 Maccabees",
    "JOB": "Job",
    "PSA": "Psalms",
    "PRO": "Proverbs",
    "ECC": "Ecclesiastes",
    "SNG": "Song of Songs",
    "WIS": "Wisdom",
    "SIR": "Sirach",
    "ISA": "Isaiah",
    "JER": "Jeremiah",
    "LAM": "Lamentations",
    "BAR": "Baruch",
    "EZK": "Ezekiel",
    "DAN": "Daniel",
    "HOS": "Hosea",
    "JOL": "Joel",
    "AMO": "Amos",
    "OBA": "Obadiah",
    "JON": "Jonah",
    "MIC": "Micah",
    "NAM": "Nahum",
    "HAB": "Habakkuk",
    "ZEP": "Zephaniah",
    "HAG": "Haggai",
    "ZEC": "Zechariah",
    "MAL": "Malachi",
    "MAT": "Matthew",
    "MRK": "Mark",
    "LUK": "Luke",
    "JHN": "John",
    "ACT": "Acts",
    "ROM": "Romans",
    "1CO": "1 Corinthians",
    "2CO": "2 Corinthians",
    "GAL": "Galatians",
    "EPH": "Ephesians",
    "PHP": "Philippians",
    "COL": "Colossians",
    "1TH": "1 Thessalonians",
    "2TH": "2 Thessalonians",
    "1TI": "1 Timothy",
    "2TI": "2 Timothy",
    "TIT": "Titus",
    "PHM": "Philemon",
    "HEB": "Hebrews",
    "JAS": "James",
    "1PE": "1 Peter",
    "2PE": "2 Peter",
    "1JN": "1 John",
    "2JN": "2 John",
    "3JN": "3 John",
    "JUD": "Jude",
    "REV": "Revelation",
}

# The Douay names for display. `douay-names.json` holds the uppercase forms the
# original prints in its margins, and title casing them produces
# `Canticle Of Canticles`. The reckoning of Kings is the Vulgate one throughout,
# where 1 and 2 Kings are Samuel and 3 and 4 Kings are what other editions call
# 1 and 2 Kings. Psalms is plural here and singular in the margin.
ENGLISH_DISPLAY = {
    "GEN": "Genesis",
    "EXO": "Exodus",
    "LEV": "Leviticus",
    "NUM": "Numbers",
    "DEU": "Deuteronomy",
    "JOS": "Josue",
    "JDG": "Judges",
    "RUT": "Ruth",
    "1SA": "1 Kings",
    "2SA": "2 Kings",
    "1KI": "3 Kings",
    "2KI": "4 Kings",
    "1CH": "1 Paralipomenon",
    "2CH": "2 Paralipomenon",
    "EZR": "1 Esdras",
    "NEH": "2 Esdras",
    "TOB": "Tobias",
    "JDT": "Judith",
    "EST": "Esther",
    "1MA": "1 Machabees",
    "2MA": "2 Machabees",
    "JOB": "Job",
    "PSA": "Psalms",
    "PRO": "Proverbs",
    "ECC": "Ecclesiastes",
    "SNG": "Canticle of Canticles",
    "WIS": "Wisdom",
    "SIR": "Ecclesiasticus",
    "ISA": "Isaias",
    "JER": "Jeremias",
    "LAM": "Lamentations",
    "BAR": "Baruch",
    "EZK": "Ezechiel",
    "DAN": "Daniel",
    "HOS": "Osee",
    "JOL": "Joel",
    "AMO": "Amos",
    "OBA": "Abdias",
    "JON": "Jonas",
    "MIC": "Micheas",
    "NAM": "Nahum",
    "HAB": "Habacuc",
    "ZEP": "Sophonias",
    "HAG": "Aggeus",
    "ZEC": "Zacharias",
    "MAL": "Malachias",
    "MAT": "Matthew",
    "MRK": "Mark",
    "LUK": "Luke",
    "JHN": "John",
    "ACT": "Acts",
    "ROM": "Romans",
    "1CO": "1 Corinthians",
    "2CO": "2 Corinthians",
    "GAL": "Galatians",
    "EPH": "Ephesians",
    "PHP": "Philippians",
    "COL": "Colossians",
    "1TH": "1 Thessalonians",
    "2TH": "2 Thessalonians",
    "1TI": "1 Timothy",
    "2TI": "2 Timothy",
    "TIT": "Titus",
    "PHM": "Philemon",
    "HEB": "Hebrews",
    "JAS": "James",
    "1PE": "1 Peter",
    "2PE": "2 Peter",
    "1JN": "1 John",
    "2JN": "2 John",
    "3JN": "3 John",
    "JUD": "Jude",
    "REV": "Apocalypse",
}

# The short form a formatted reference prints. Nothing upstream carries these,
# in any language but Portuguese, so all 146 are authored here.
#
# `Ecclus.` is Ecclesiasticus and `Eccles.` is Ecclesiastes, which is the pair an
# English reader mixes up and the reason the abbreviations are checked against
# the names rather than eyeballed.
ENGLISH_ABBREVIATIONS = {
    "GEN": "Gen.",
    "EXO": "Ex.",
    "LEV": "Lev.",
    "NUM": "Num.",
    "DEU": "Deut.",
    "JOS": "Jos.",
    "JDG": "Judg.",
    "RUT": "Ruth",
    "1SA": "1 Kgs.",
    "2SA": "2 Kgs.",
    "1KI": "3 Kgs.",
    "2KI": "4 Kgs.",
    "1CH": "1 Par.",
    "2CH": "2 Par.",
    "EZR": "1 Esd.",
    "NEH": "2 Esd.",
    "TOB": "Tob.",
    "JDT": "Jdt.",
    "EST": "Esth.",
    "1MA": "1 Mach.",
    "2MA": "2 Mach.",
    "JOB": "Job",
    "PSA": "Ps.",
    "PRO": "Prov.",
    "ECC": "Eccles.",
    "SNG": "Cant.",
    "WIS": "Wis.",
    "SIR": "Ecclus.",
    "ISA": "Is.",
    "JER": "Jer.",
    "LAM": "Lam.",
    "BAR": "Bar.",
    "EZK": "Ezech.",
    "DAN": "Dan.",
    "HOS": "Os.",
    "JOL": "Joel",
    "AMO": "Amos",
    "OBA": "Abd.",
    "JON": "Jon.",
    "MIC": "Mich.",
    "NAM": "Nah.",
    "HAB": "Hab.",
    "ZEP": "Soph.",
    "HAG": "Agg.",
    "ZEC": "Zach.",
    "MAL": "Mal.",
    "MAT": "Matt.",
    "MRK": "Mark",
    "LUK": "Luke",
    "JHN": "John",
    "ACT": "Acts",
    "ROM": "Rom.",
    "1CO": "1 Cor.",
    "2CO": "2 Cor.",
    "GAL": "Gal.",
    "EPH": "Eph.",
    "PHP": "Phil.",
    "COL": "Col.",
    "1TH": "1 Thess.",
    "2TH": "2 Thess.",
    "1TI": "1 Tim.",
    "2TI": "2 Tim.",
    "TIT": "Tit.",
    "PHM": "Philem.",
    "HEB": "Heb.",
    "JAS": "Jas.",
    "1PE": "1 Pet.",
    "2PE": "2 Pet.",
    "1JN": "1 John",
    "2JN": "2 John",
    "3JN": "3 John",
    "JUD": "Jude",
    "REV": "Apoc.",
}

# Roman numerals, because that is how the Vulgate prints them and how the Latin
# names in this file already read.
LATIN_ABBREVIATIONS = {
    "GEN": "Gen.",
    "EXO": "Ex.",
    "LEV": "Lev.",
    "NUM": "Num.",
    "DEU": "Deut.",
    "JOS": "Ios.",
    "JDG": "Iudic.",
    "RUT": "Ruth",
    "1SA": "I Reg.",
    "2SA": "II Reg.",
    "1KI": "III Reg.",
    "2KI": "IV Reg.",
    "1CH": "I Par.",
    "2CH": "II Par.",
    "EZR": "Esdr.",
    "NEH": "Neh.",
    "TOB": "Tob.",
    "JDT": "Iudith",
    "EST": "Esth.",
    "1MA": "I Mach.",
    "2MA": "II Mach.",
    "JOB": "Iob",
    "PSA": "Ps.",
    "PRO": "Prov.",
    "ECC": "Eccle.",
    "SNG": "Cant.",
    "WIS": "Sap.",
    "SIR": "Eccli.",
    "ISA": "Is.",
    "JER": "Ier.",
    "LAM": "Lam.",
    "BAR": "Bar.",
    "EZK": "Ezech.",
    "DAN": "Dan.",
    "HOS": "Os.",
    "JOL": "Ioel",
    "AMO": "Am.",
    "OBA": "Abd.",
    "JON": "Ion.",
    "MIC": "Mich.",
    "NAM": "Nah.",
    "HAB": "Hab.",
    "ZEP": "Soph.",
    "HAG": "Agg.",
    "ZEC": "Zach.",
    "MAL": "Mal.",
    "MAT": "Matth.",
    "MRK": "Marc.",
    "LUK": "Luc.",
    "JHN": "Ioan.",
    "ACT": "Act.",
    "ROM": "Rom.",
    "1CO": "I Cor.",
    "2CO": "II Cor.",
    "GAL": "Gal.",
    "EPH": "Eph.",
    "PHP": "Philipp.",
    "COL": "Col.",
    "1TH": "I Thess.",
    "2TH": "II Thess.",
    "1TI": "I Tim.",
    "2TI": "II Tim.",
    "TIT": "Tit.",
    "PHM": "Philem.",
    "HEB": "Hebr.",
    "JAS": "Iac.",
    "1PE": "I Petr.",
    "2PE": "II Petr.",
    "1JN": "I Ioan.",
    "2JN": "II Ioan.",
    "3JN": "III Ioan.",
    "JUD": "Iudae",
    "REV": "Apoc.",
}
