"""Book names authored here rather than exported.

Everything else in this package comes out of the private source repository. Two
things do not exist there and are written here instead, so they live in code
where a reviewer reads them as a decision rather than in JSON where they would
look like data somebody generated.

Latin follows liturgical usage. Where the tradition carries more than one form
the liturgical one is canonical and the alternative is an alias, so nothing is
decided by silence. The books of Kings keep the Vulgate reckoning, in which
I and II Regum are Samuel, which is the same reckoning the Douay names use.

Modern English is here because the exported Douay names are the canonical
English and a reader who types `Joshua` should still land in Josue.
"""

LATIN_NAMES = {
    "GEN": "Genesis",
    "EXO": "Exodus",
    "LEV": "Leviticus",
    "NUM": "Numeri",
    "DEU": "Deuteronomium",
    "JOS": "Iosue",
    "JDG": "Iudicum",
    "RUT": "Ruth",
    "1SA": "I Regum",
    "2SA": "II Regum",
    "1KI": "III Regum",
    "2KI": "IV Regum",
    "1CH": "I Paralipomenon",
    "2CH": "II Paralipomenon",
    "EZR": "Esdrae",
    "NEH": "Nehemiae",
    "TOB": "Tobiae",
    "JDT": "Iudith",
    "EST": "Esther",
    "1MA": "I Machabaeorum",
    "2MA": "II Machabaeorum",
    "JOB": "Iob",
    "PSA": "Psalmi",
    "PRO": "Proverbia",
    "ECC": "Ecclesiastes",
    "SNG": "Canticum Canticorum",
    "WIS": "Sapientia",
    "SIR": "Ecclesiasticus",
    "ISA": "Isaias",
    "JER": "Ieremias",
    "LAM": "Lamentationes",
    "BAR": "Baruch",
    "EZK": "Ezechiel",
    "DAN": "Daniel",
    "HOS": "Osee",
    "JOL": "Ioel",
    "AMO": "Amos",
    "OBA": "Abdias",
    "JON": "Ionas",
    "MIC": "Michaeas",
    "NAM": "Nahum",
    "HAB": "Habacuc",
    "ZEP": "Sophonias",
    "HAG": "Aggaeus",
    "ZEC": "Zacharias",
    "MAL": "Malachias",
    "MAT": "Matthaeus",
    "MRK": "Marcus",
    "LUK": "Lucas",
    "JHN": "Ioannes",
    "ACT": "Actus Apostolorum",
    "ROM": "Ad Romanos",
    "1CO": "I Ad Corinthios",
    "2CO": "II Ad Corinthios",
    "GAL": "Ad Galatas",
    "EPH": "Ad Ephesios",
    "PHP": "Ad Philippenses",
    "COL": "Ad Colossenses",
    "1TH": "I Ad Thessalonicenses",
    "2TH": "II Ad Thessalonicenses",
    "1TI": "I Ad Timotheum",
    "2TI": "II Ad Timotheum",
    "TIT": "Ad Titum",
    "PHM": "Ad Philemonem",
    "HEB": "Ad Hebraeos",
    "JAS": "Iacobi",
    "1PE": "I Petri",
    "2PE": "II Petri",
    "1JN": "I Ioannis",
    "2JN": "II Ioannis",
    "3JN": "III Ioannis",
    "JUD": "Iudae",
    "REV": "Apocalypsis",
}

LATIN_ALIASES = {
    "1SA": ("I Samuelis",),
    "2SA": ("II Samuelis",),
    "NEH": ("II Esdrae",),
    "EZR": ("I Esdrae",),
    "SIR": ("Siracides", "Liber Ecclesiastici"),
    "SNG": ("Canticum", "Cantica Canticorum"),
    "REV": ("Revelatio",),
    "LAM": ("Threni",),
    "ECC": ("Qoheleth",),
    "ACT": ("Acta Apostolorum",),
}

ENGLISH_MODERN = {
    "GEN": "Genesis",
    "EXO": "Exodus",
    "LEV": "Leviticus",
    "NUM": "Numbers",
    "DEU": "Deuteronomy",
    "JOS": "Joshua",
    "JDG": "Judges",
    "RUT": "Ruth",
    "1SA": "1 Samuel",
    "2SA": "2 Samuel",
    "1KI": "1 Kings",
    "2KI": "2 Kings",
    "1CH": "1 Chronicles",
    "2CH": "2 Chronicles",
    "EZR": "Ezra",
    "NEH": "Nehemiah",
    "TOB": "Tobit",
    "JDT": "Judith",
    "EST": "Esther",
    "1MA": "1 Maccabees",
    "2MA": "2 Maccabees",
    "JOB": "Job",
    "PSA": "Psalms",
    "PRO": "Proverbs",
    "ECC": "Ecclesiastes",
    "SNG": "Song of Songs",
    "WIS": "Wisdom",
    "SIR": "Sirach",
    "ISA": "Isaiah",
    "JER": "Jeremiah",
    "LAM": "Lamentations",
    "BAR": "Baruch",
    "EZK": "Ezekiel",
    "DAN": "Daniel",
    "HOS": "Hosea",
    "JOL": "Joel",
    "AMO": "Amos",
    "OBA": "Obadiah",
    "JON": "Jonah",
    "MIC": "Micah",
    "NAM": "Nahum",
    "HAB": "Habakkuk",
    "ZEP": "Zephaniah",
    "HAG": "Haggai",
    "ZEC": "Zechariah",
    "MAL": "Malachi",
    "MAT": "Matthew",
    "MRK": "Mark",
    "LUK": "Luke",
    "JHN": "John",
    "ACT": "Acts",
    "ROM": "Romans",
    "1CO": "1 Corinthians",
    "2CO": "2 Corinthians",
    "GAL": "Galatians",
    "EPH": "Ephesians",
    "PHP": "Philippians",
    "COL": "Colossians",
    "1TH": "1 Thessalonians",
    "2TH": "2 Thessalonians",
    "1TI": "1 Timothy",
    "2TI": "2 Timothy",
    "TIT": "Titus",
    "PHM": "Philemon",
    "HEB": "Hebrews",
    "JAS": "James",
    "1PE": "1 Peter",
    "2PE": "2 Peter",
    "1JN": "1 John",
    "2JN": "2 John",
    "3JN": "3 John",
    "JUD": "Jude",
    "REV": "Revelation",
}
